version: '3.8'

services:
  excel-service:
    build: .
    ports:
      - "5015:5014"
    environment:
      - S3_BUCKET=excel-files
      - S3_REGION=us-east-1
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_ENDPOINT_URL=http://minio:9000
      - URL_EXPIRY_HOURS=24
    depends_on:
      minio:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - temp_uploads:/app/temp_uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5014/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s

volumes:
  minio_data:
  temp_uploads:
